### ISSUE TITLE
dist/ exports are stock Bootstrap

### ISSUE THREAD

**Issue by davisable** [wilwaldon/flatstrap#54]
The CSS files in /dist/ have rounded buttons and such (plain bootstrap) -- this is mentioned in #51 but that has been closed.

https://github.com/littlesparkvt/flatstrap/blob/master/dist/css/flatstrap.css

``` css
.btn {
 [...removed..]
  border: 1px solid transparent;
  border-radius: 4px;
}
```

And here's the same btn class being used on the Flatstrap website (no border radius):

``` css
.btn {
  border-color: #e6e6e6 #e6e6e6 #bfbfbf;
  border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
  border-bottom-color: #a2a2a2;
}
```
